version: '3.7'
services:
  db:
    image: mysql:5.7
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    ports:
      - "3387:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - my_app
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './apps/my-symfony-app/:/usr/src/app'
    user: ${LOCAL_USER}
    networks:
      - my_app

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './apps/my-symfony-app/public/:/usr/src/app'
      - './apps/my-symfony-app/:/usr/src'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php
    networks:
      - my_app
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: interface-public-pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 6081:80 
    networks:
      - my_app

networks:
  my_app:
    driver: bridge
